// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: operation-system.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendOperationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserName string       `protobuf:"bytes,1,opt,name=UserName,proto3" json:"UserName,omitempty"` // 用户信息
	Context  *UserContext `protobuf:"bytes,2,opt,name=Context,proto3" json:"Context,omitempty"`
}

func (x *SendOperationRequest) Reset() {
	*x = SendOperationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operation_system_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOperationRequest) ProtoMessage() {}

func (x *SendOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operation_system_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOperationRequest.ProtoReflect.Descriptor instead.
func (*SendOperationRequest) Descriptor() ([]byte, []int) {
	return file_operation_system_proto_rawDescGZIP(), []int{0}
}

func (x *SendOperationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *SendOperationRequest) GetContext() *UserContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type SendOperationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"` // 是否成功
}

func (x *SendOperationResponse) Reset() {
	*x = SendOperationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_operation_system_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOperationResponse) ProtoMessage() {}

func (x *SendOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operation_system_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOperationResponse.ProtoReflect.Descriptor instead.
func (*SendOperationResponse) Descriptor() ([]byte, []int) {
	return file_operation_system_proto_rawDescGZIP(), []int{1}
}

func (x *SendOperationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_operation_system_proto protoreflect.FileDescriptor

var file_operation_system_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x67, 0x72,
	0x70, 0x63, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a,
	0x14, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x29, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x22, 0x31, 0x0a, 0x15,
	0x53, 0x65, 0x6e, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32,
	0x56, 0x0a, 0x0f, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x12, 0x43, 0x0a, 0x19, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x46, 0x6f, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x18, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_operation_system_proto_rawDescOnce sync.Once
	file_operation_system_proto_rawDescData = file_operation_system_proto_rawDesc
)

func file_operation_system_proto_rawDescGZIP() []byte {
	file_operation_system_proto_rawDescOnce.Do(func() {
		file_operation_system_proto_rawDescData = protoimpl.X.CompressGZIP(file_operation_system_proto_rawDescData)
	})
	return file_operation_system_proto_rawDescData
}

var file_operation_system_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_operation_system_proto_goTypes = []interface{}{
	(*SendOperationRequest)(nil),  // 0: pb.SendOperationRequest
	(*SendOperationResponse)(nil), // 1: pb.SendOperationResponse
	(*UserContext)(nil),           // 2: pb.UserContext
	(*Response)(nil),              // 3: pb.Response
}
var file_operation_system_proto_depIdxs = []int32{
	2, // 0: pb.SendOperationRequest.Context:type_name -> pb.UserContext
	0, // 1: pb.OperationSystem.SendOperationForLoginUser:input_type -> pb.SendOperationRequest
	3, // 2: pb.OperationSystem.SendOperationForLoginUser:output_type -> pb.Response
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_operation_system_proto_init() }
func file_operation_system_proto_init() {
	if File_operation_system_proto != nil {
		return
	}
	file_grpc_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_operation_system_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOperationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_operation_system_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendOperationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_operation_system_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operation_system_proto_goTypes,
		DependencyIndexes: file_operation_system_proto_depIdxs,
		MessageInfos:      file_operation_system_proto_msgTypes,
	}.Build()
	File_operation_system_proto = out.File
	file_operation_system_proto_rawDesc = nil
	file_operation_system_proto_goTypes = nil
	file_operation_system_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OperationSystemClient is the client API for OperationSystem service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OperationSystemClient interface {
	SendOperationForLoginUser(ctx context.Context, in *SendOperationRequest, opts ...grpc.CallOption) (*Response, error)
}

type operationSystemClient struct {
	cc grpc.ClientConnInterface
}

func NewOperationSystemClient(cc grpc.ClientConnInterface) OperationSystemClient {
	return &operationSystemClient{cc}
}

func (c *operationSystemClient) SendOperationForLoginUser(ctx context.Context, in *SendOperationRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.OperationSystem/SendOperationForLoginUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperationSystemServer is the server API for OperationSystem service.
type OperationSystemServer interface {
	SendOperationForLoginUser(context.Context, *SendOperationRequest) (*Response, error)
}

// UnimplementedOperationSystemServer can be embedded to have forward compatible implementations.
type UnimplementedOperationSystemServer struct {
}

func (*UnimplementedOperationSystemServer) SendOperationForLoginUser(context.Context, *SendOperationRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOperationForLoginUser not implemented")
}

func RegisterOperationSystemServer(s *grpc.Server, srv OperationSystemServer) {
	s.RegisterService(&_OperationSystem_serviceDesc, srv)
}

func _OperationSystem_SendOperationForLoginUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperationSystemServer).SendOperationForLoginUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OperationSystem/SendOperationForLoginUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperationSystemServer).SendOperationForLoginUser(ctx, req.(*SendOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OperationSystem_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OperationSystem",
	HandlerType: (*OperationSystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOperationForLoginUser",
			Handler:    _OperationSystem_SendOperationForLoginUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operation-system.proto",
}
