// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by grpc_generate_tools(grpcgengo) at
//
package officiallistener

import (
	"context"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"
	"log"

	"gitlab.flyele.vip/server-side/go-zero/v2/rpcx/grpcbase"
)

//GrpcClient grpc客户端，各服务无需重复开发客户端。
// 如果对response有特殊处理，请在该文件夹下新增 response.go 处理后续逻辑
type GrpcClient struct {
	client Repository
}

//NewClient officiallistener GRPC客户端实例
func NewClient() GrpcClient {
	c, err := grpcbase.DialClient(grpcbase.ServerAddr(grpcbase.OfficialListenerSVC))
	if err != nil {
		log.Fatal(err)
	}
	client := c.(Repository)
	return GrpcClient{client}
}

// HandleSendMessage 客户端处理逻辑
func (c *GrpcClient) HandleSendMessage(ctx context.Context, req SendMessageRequest) *SendMessageResponse {
	if req.Context == nil {
		panic("grpc context is nil and requestID must be set")
	}
	ctx1, span, requestID := grpcbase.NewTraceSpanFromRequestID("client", "/pb.officiallistener/SendMessage", req.Context.RequestID)
	defer span.End()

	span.SetAttributes(attribute.String("message.id", req.Context.RequestID))
	span.SetAttributes(attribute.String("user.id", req.Context.UserID))

	span.AddEvent("request", trace.WithAttributes(attribute.String("message.data", req.String())))
	req.Context.RequestID = requestID

	resp := c.client.SendMessage(ctx1, req)
	if resp.Message != "" {
		log.Println("ERROR：请求 SendMessage 失败，error：" + resp.Message)
		return nil
	}
	if resp.Data != nil {
		var m = resp.Data.(SendMessageResponse)
		return &m
	}
	return nil
}

// HandleSendCorpTempMsg 客户端处理逻辑
func (c *GrpcClient) HandleSendCorpTempMsg(ctx context.Context, req SendCorpTempMsgRequest) *SendCorpTempMsgResponse {
	if req.Context == nil {
		panic("grpc context is nil and requestID must be set")
	}
	ctx1, span, requestID := grpcbase.NewTraceSpanFromRequestID("client", "/pb.officiallistener/SendCorpTempMsg", req.Context.RequestID)
	defer span.End()

	span.SetAttributes(attribute.String("message.id", req.Context.RequestID))
	span.SetAttributes(attribute.String("user.id", req.Context.UserID))

	span.AddEvent("request", trace.WithAttributes(attribute.String("message.data", req.String())))
	req.Context.RequestID = requestID

	resp := c.client.SendCorpTempMsg(ctx1, req)
	if resp.Message != "" {
		log.Println("ERROR：请求 SendCorpTempMsg 失败，error：" + resp.Message)
		return nil
	}
	if resp.Data != nil {
		var m = resp.Data.(SendCorpTempMsgResponse)
		return &m
	}
	return nil
}

// HandleGetUserCorpDetail 客户端处理逻辑
func (c *GrpcClient) HandleGetUserCorpDetail(ctx context.Context, req GetUserCorpDetailRequest) *GetUserCorpDetailResponse {
	if req.Context == nil {
		panic("grpc context is nil and requestID must be set")
	}
	ctx1, span, requestID := grpcbase.NewTraceSpanFromRequestID("client", "/pb.officiallistener/GetUserCorpDetail", req.Context.RequestID)
	defer span.End()

	span.SetAttributes(attribute.String("message.id", req.Context.RequestID))
	span.SetAttributes(attribute.String("user.id", req.Context.UserID))

	span.AddEvent("request", trace.WithAttributes(attribute.String("message.data", req.String())))
	req.Context.RequestID = requestID

	resp := c.client.GetUserCorpDetail(ctx1, req)
	if resp.Message != "" {
		log.Println("ERROR：请求 GetUserCorpDetail 失败，error：" + resp.Message)
		return nil
	}
	if resp.Data != nil {
		var m = resp.Data.(GetUserCorpDetailResponse)
		return &m
	}
	return nil
}

// HandleBatchGetCorpDetail 客户端处理逻辑
func (c *GrpcClient) HandleBatchGetCorpDetail(ctx context.Context, req BatchGetCorpDetailRequest) *BatchGetCorpDetailResponse {
	if req.Context == nil {
		panic("grpc context is nil and requestID must be set")
	}
	ctx1, span, requestID := grpcbase.NewTraceSpanFromRequestID("client", "/pb.officiallistener/BatchGetCorpDetail", req.Context.RequestID)
	defer span.End()

	span.SetAttributes(attribute.String("message.id", req.Context.RequestID))
	span.SetAttributes(attribute.String("user.id", req.Context.UserID))

	span.AddEvent("request", trace.WithAttributes(attribute.String("message.data", req.String())))
	req.Context.RequestID = requestID

	resp := c.client.BatchGetCorpDetail(ctx1, req)
	if resp.Message != "" {
		log.Println("ERROR：请求 BatchGetCorpDetail 失败，error：" + resp.Message)
		return nil
	}
	if resp.Data != nil {
		var m = resp.Data.(BatchGetCorpDetailResponse)
		return &m
	}
	return nil
}
