// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by grpc_generate_tools(grpcgengo) at
//
package operationsystem

import (
	"context"
	"errors"
	"log"

	"gitlab.flyele.vip/server-side/go-zero/v2/rpcx/grpcbase"
)

//GrpcClient grpc客户端，各服务无需重复开发客户端。
// 如果对response有特殊处理，请在该文件夹下新增 response.go 处理后续逻辑
type GrpcClient struct {
	client Repository
}

//NewClient operationsystem GRPC客户端实例
func NewClient() GrpcClient {
	c, err := grpcbase.DialClient(grpcbase.ServerAddr(grpcbase.OperationSystemSVC))
	if err != nil {
		log.Fatal(err)
	}
	client := c.(Repository)
	return GrpcClient{client}
}

// HandleSendOperationForLoginUser 客户端处理逻辑
func (c *GrpcClient) HandleSendOperationForLoginUser(ctx context.Context, req SendOperationRequest) error {
	resp := c.client.SendOperationForLoginUser(ctx, req)
	if resp.Message != "" {
		return errors.New(resp.Message)
	}
	return nil
}
