// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by grpc_generate_tools(grpcgengo) at
//

package pushgateway

import (
	"context"
	"log"

	grpctransport "github.com/go-kit/kit/transport/grpc"
	"gitlab.flyele.vip/server-side/go-zero/v2/rpcx/grpcbase"
	pb "gitlab.flyele.vip/server-side/go-zero/v2/rpcx/protos"
	"google.golang.org/grpc"
)

type serverBinding struct {
	websocketOnline grpctransport.Handler
}

func (b *serverBinding) WebsocketOnline(ctx context.Context, req *pb.WebsocketOnlineRequest) (*pb.Response, error) {
	if ctx == nil {
		ctx = context.Background()
		log.Println("GRPC：WebsocketOnline receive request context is nil，trace span将无法生效")
	}
	_, response, err := b.websocketOnline.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Response), nil
}

func (b *serverBinding) RegisterServer(srv *grpc.Server) error {
	pb.RegisterPushGatewayServer(srv, b)
	return nil
}

func (b *serverBinding) GRPCHandler() map[string]grpctransport.Handler {
	return map[string]grpctransport.Handler{
		"websocketOnline": b.websocketOnline,
	}
}

func NewBinding(svc Repository) *serverBinding {
	return &serverBinding{
		websocketOnline: grpcbase.CreateGRPCServer(
			makeWebsocketOnlineEndpoint(svc),
			decodeWebsocketOnlineRequest,
			encodeWebsocketOnlineResponse,
		),
	}
}
