// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by grpc_generate_tools(grpcgengo) at
//

package pushgateway

import (
	"context"
	"log"

	"github.com/go-kit/kit/endpoint"
	"gitlab.flyele.vip/server-side/go-zero/v2/rpcx/grpcbase"
	"google.golang.org/grpc"
)

func init() {
	grpcbase.RegisterClients(grpcbase.ServerAddr(grpcbase.PushGatewaySVC), &clientBinding{})
}

type clientBinding struct {
	websocketOnline endpoint.Endpoint
}

func (c *clientBinding) WebsocketOnline(ctx context.Context, params WebsocketOnlineRequest) grpcbase.Response {
	if ctx == nil {
		ctx = context.Background()
		log.Println("GRPC：WebsocketOnline request context is nil，trace span将无法生效")
	}
	response, err := c.websocketOnline(ctx, params)
	if err != nil {
		return grpcbase.Response{
			Message: err.Error(),
		}
	}
	r := response.(grpcbase.Response)
	return r
}

func (c *clientBinding) GRPCClient(cc *grpc.ClientConn) interface{} {
	c.newClient(cc)
	return c
}

func (c *clientBinding) newClient(cc *grpc.ClientConn) {

	c.websocketOnline = grpcbase.CreateGRPCClientEndpoint(cc, "pb.PushGateway",
		"WebsocketOnline",
		encodeWebsocketOnlineRequest,
		decodeWebsocketOnlineResponse)
}
